[package]
name = "ibento-rs"
version = "0.1.0"
authors = ["Blaž Hrastnik <blaz@mxxn.io>"]
edition = "2018"

[lib]
name = "ibento"

[[bin]]
name = "ibento-server"
path = "src/bin/server.rs"

[[bin]]
name = "ibento-client"
path = "src/bin/client.rs"

[dependencies]
# futures01 = { package = "futures", version = "0.1" }
futures-preview = {git = "https://github.com/rust-lang-nursery/futures-rs/", features = ["compat", "io-compat", "async-await", "nightly"]}
bytes = "0.4"
env_logger = { version = "0.6.1", default-features = false }
log = "0.4"
http = "0.1"
# prost = "0.5"
# prost-types = "0.5"
prost = { git = "https://github.com/archseer/prost" }
prost-types = { git = "https://github.com/archseer/prost", features = ["serde_json"] }
tokio = "0.1"
tokio-trace = "0.1.0"
tokio-trace-tower-http = { git = "https://github.com/tokio-rs/tokio-trace-nursery" }
tokio-trace-fmt = { git = "https://github.com/tokio-rs/tokio-trace-nursery" }
tokio-trace-futures = { git = "https://github.com/tokio-rs/tokio-trace-nursery" }
tower-request-modifier = { git = "https://github.com/tower-rs/tower-http" }
tower-grpc = { git = "https://github.com/tower-rs/tower-grpc", features = ["tower-hyper"] }
tower-hyper = { git = "https://github.com/tower-rs/tower-hyper" }
hyper = "0.12"
tower-service = "0.2"
tower-util = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
maplit = "1.0.1"
# runtime = "0.3.0-alpha.4"
# runtime-tokio = "0.3.0-alpha.4"
diesel = { version = "1.0.0", features = ["postgres", "r2d2", "uuidv07", "chrono", "serde_json"] }
dotenv = "0.14.0"
r2d2 = "0.8.4"
tokio-threadpool = "0.1.14"
chrono = "0.4.6"
uuid = "0.7.4"

[patch.crates-io]
prost = { git = "https://github.com/archseer/prost", features = ["serde_json"] }
prost-build = { git = "https://github.com/archseer/prost" }

[build-dependencies]
tower-grpc-build = { git = "https://github.com/LucioFranco/tower-grpc/", branch = "hyper", features = ["tower-hyper"] }
prost-build = { git = "https://github.com/archseer/prost" }
